"""Compatibility exports for the original shared helper API."""

from re_engine_binary import (
	sha256_bytes,
	checked_range,
	read_scalar,
	read_utf16z,
	ranges_overlap,
)

from re_engine_math import (
	float32,
	round_half_away_from_zero,
	round_shift_right_to_even,
	float_to_half_bits,
	quantize_snorm,
	quantize_color,
	quantize_weights,
	_validate_bone_map_count,
	pack_six_u10,
	decode_six_u10,
	validate_vector,
	transform_point_row_vector,
	topology_hash,
)

from re_engine_motlist_1057 import (
	MOTLIST_1057_VERSION,
	MOT_993_VERSION,
	MTRE_22_VERSION,
	MOTLIST_1057_HEADER_SIZE,
	MOT_993_HEADER_SIZE,
	MOTLIST_BONE_ROW_SIZE,
	MOTLIST_CLIP_ROW_SIZE,
	MOTLIST_TRACK_DESCRIPTOR_SIZE,
	MOTLIST_TRACK_DESCRIPTOR_COUNT,
	MOTLIST_TRACK_HEADER_SIZE,
	MOTLIST_MOTION_ID_ROW_SIZE,
	_motlist_fail,
	_motlist_source_basename,
	_motlist_read_utf16z,
	_motlist_relative_offset,
	parse_pragmata_motlist_1057_multi,
	parse_pragmata_motlist_1057_exact,
	_MOTLIST_ANIMATION_VALUE_WIDTH,
	_MOTLIST_ANIMATION_FLAG_SUFFIX,
	_MOTLIST_ANIMATION_EXACT_IDENTITIES,
	_MOTLIST_ANIMATION_INDEX_FORMAT,
	_MOTLIST_1057_OBSERVED_FULL_FLAGS,
	_motlist_animation_canonical_time_sha256,
	_motlist_animation_canonical_value_sha256,
	_motlist_animation_normalize_rotation_xyz,
	_motlist_animation_normalize_bind_rotation,
	_motlist_animation_decode_times,
	_motlist_animation_packed_components,
	_motlist_animation_decode_rotation_components,
	_motlist_animation_decode_value,
	_motlist_animation_decode_track,
	_motlist_multi_action_header,
	_motlist_multi_carrier_bones,
	_motlist_multi_descriptors,
	_decode_motlist_1057_multi,
	decode_pragmata_motlist_1057_multi,
	_decode_motlist_1057_exact,
	decode_pragmata_motlist_1057_exact,
)
